//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emelyanenko_AdManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adverts
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Ad_Title { get; set; }
        public string Ad_Description { get; set; }
        public Nullable<System.DateTime> Ad_Post_Date { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Ad_TypeID { get; set; }
        public Nullable<int> Ad_StatusID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Ad_Statuses Ad_Statuses { get; set; }
        public virtual Ad_Types Ad_Types { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Users Users { get; set; }
    }
}
