//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emelyanenko_AdManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Emelyanenko_AdManagementEntities : DbContext
    {
        public Emelyanenko_AdManagementEntities()
            : base("name=Emelyanenko_AdManagementEntities")
        {
        }

        static private Emelyanenko_AdManagementEntities instance;

        static public Emelyanenko_AdManagementEntities getInstance()
        {
            if (instance == null)
            {
                instance = new Emelyanenko_AdManagementEntities();
            }
            return instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad_Statuses> Ad_Statuses { get; set; }
        public virtual DbSet<Ad_Types> Ad_Types { get; set; }
        public virtual DbSet<Adverts> Adverts { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
