CREATE DATABASE Emelyanenko_AdManagement;

GO

USE Emelyanenko_AdManagement;

CREATE TABLE Users (ID INT PRIMARY KEY IDENTITY(0, 1), User_Login VARCHAR(250) UNIQUE NOT NULL, User_Password VARCHAR(250) NOT NULL);
CREATE TABLE Cities (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(250) NOT NULL);
CREATE TABLE Categories (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(250) NOT NULL);
CREATE TABLE Ad_Types (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(250) NOT NULL);
CREATE TABLE Ad_Statuses (ID INT PRIMARY KEY IDENTITY(0, 1), Name VARCHAR(250) NOT NULL);
CREATE TABLE Adverts (ID INT PRIMARY KEY IDENTITY(0, 1), UserID INT REFERENCES Users NOT NULL, Ad_Title VARCHAR(250) NOT NULL, Ad_Description VARCHAR(500) NOT NULL, Ad_Post_Date DATE NOT NULL, CityID INT REFERENCES Cities NOT NULL, CategoryID INT REFERENCES Categories NOT NULL, Ad_TypeID INT REFERENCES Ad_Types NOT NULL, Ad_StatusID INT REFERENCES Ad_Statuses NOT NULL, Price INT NOT NULL, PhotoPath VARCHAR(500));