//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emelyanenko_AdManagement
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Adverts = new HashSet<Adverts>();
        }
    
        public int ID { get; set; }
        public string User_Login { get; set; }
        public string User_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adverts> Adverts { get; set; }
        // Свойство для получения суммы выручки со всех завершенных объявлений данного пользователя
        public Nullable<int> Finished_Ad_Sum
        {
            get
            {
                return Emelyanenko_AdManagementEntities.getInstance().Adverts.Where(entry => entry.UserID == this.ID && entry.Ad_Statuses.Name == "Завершено").Sum(entry => entry.Price);
            }
        } 
    }
}
